# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: float_exchange.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'float_exchange.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66loat_exchange.proto\x12\rfloatexchange\"8\n\x0c\x46loatRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x02\x12\x0c\n\x04num2\x18\x02 \x01(\x02\x12\x0c\n\x04num3\x18\x03 \x01(\x02\"B\n\rFloatResponse\x12\x0f\n\x07result1\x18\x01 \x01(\x02\x12\x0f\n\x07result2\x18\x02 \x01(\x02\x12\x0f\n\x07result3\x18\x03 \x01(\x02\x32X\n\rFloatExchange\x12G\n\nSendFloats\x12\x1b.floatexchange.FloatRequest\x1a\x1c.floatexchange.FloatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'float_exchange_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FLOATREQUEST']._serialized_start=39
  _globals['_FLOATREQUEST']._serialized_end=95
  _globals['_FLOATRESPONSE']._serialized_start=97
  _globals['_FLOATRESPONSE']._serialized_end=163
  _globals['_FLOATEXCHANGE']._serialized_start=165
  _globals['_FLOATEXCHANGE']._serialized_end=253
# @@protoc_insertion_point(module_scope)
