// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: float_exchange.proto
#ifndef GRPC_float_5fexchange_2eproto__INCLUDED
#define GRPC_float_5fexchange_2eproto__INCLUDED

#include "float_exchange.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace floatexchange {

// 서비스 정의
class FloatExchange final {
 public:
  static constexpr char const* service_full_name() {
    return "floatexchange.FloatExchange";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SendFloats(::grpc::ClientContext* context, const ::floatexchange::FloatRequest& request, ::floatexchange::FloatResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::floatexchange::FloatResponse>> AsyncSendFloats(::grpc::ClientContext* context, const ::floatexchange::FloatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::floatexchange::FloatResponse>>(AsyncSendFloatsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::floatexchange::FloatResponse>> PrepareAsyncSendFloats(::grpc::ClientContext* context, const ::floatexchange::FloatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::floatexchange::FloatResponse>>(PrepareAsyncSendFloatsRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void SendFloats(::grpc::ClientContext* context, const ::floatexchange::FloatRequest* request, ::floatexchange::FloatResponse* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::floatexchange::FloatResponse>* AsyncSendFloatsRaw(::grpc::ClientContext* context, const ::floatexchange::FloatRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::floatexchange::FloatResponse>* PrepareAsyncSendFloatsRaw(::grpc::ClientContext* context, const ::floatexchange::FloatRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status SendFloats(::grpc::ClientContext* context, const ::floatexchange::FloatRequest& request, ::floatexchange::FloatResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::floatexchange::FloatResponse>> AsyncSendFloats(::grpc::ClientContext* context, const ::floatexchange::FloatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::floatexchange::FloatResponse>>(AsyncSendFloatsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::floatexchange::FloatResponse>> PrepareAsyncSendFloats(::grpc::ClientContext* context, const ::floatexchange::FloatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::floatexchange::FloatResponse>>(PrepareAsyncSendFloatsRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void SendFloats(::grpc::ClientContext* context, const ::floatexchange::FloatRequest* request, ::floatexchange::FloatResponse* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::floatexchange::FloatResponse>* AsyncSendFloatsRaw(::grpc::ClientContext* context, const ::floatexchange::FloatRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::floatexchange::FloatResponse>* PrepareAsyncSendFloatsRaw(::grpc::ClientContext* context, const ::floatexchange::FloatRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendFloats_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SendFloats(::grpc::ServerContext* context, const ::floatexchange::FloatRequest* request, ::floatexchange::FloatResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendFloats : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_SendFloats() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendFloats() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendFloats(::grpc::ServerContext* context, const ::floatexchange::FloatRequest* request, ::floatexchange::FloatResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendFloats(::grpc::ServerContext* context, ::floatexchange::FloatRequest* request, ::grpc::ServerAsyncResponseWriter< ::floatexchange::FloatResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendFloats<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_SendFloats : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_SendFloats() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendFloats() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendFloats(::grpc::ServerContext* context, const ::floatexchange::FloatRequest* request, ::floatexchange::FloatResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendFloats : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_SendFloats() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendFloats() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendFloats(::grpc::ServerContext* context, const ::floatexchange::FloatRequest* request, ::floatexchange::FloatResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendFloats(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendFloats : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_SendFloats() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::floatexchange::FloatRequest, ::floatexchange::FloatResponse>(std::bind(&WithStreamedUnaryMethod_SendFloats<BaseClass>::StreamedSendFloats, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_SendFloats() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendFloats(::grpc::ServerContext* context, const ::floatexchange::FloatRequest* request, ::floatexchange::FloatResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendFloats(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::floatexchange::FloatRequest,::floatexchange::FloatResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendFloats<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendFloats<Service > StreamedService;
};

}  // namespace floatexchange


#endif  // GRPC_float_5fexchange_2eproto__INCLUDED
